module.exports.input = {
    address: 'address',
    amount: 'amount',
    approved: 'approved',
    category: 'category',
    commercialId: 'commercialId',
    country: 'country',
    duration: 'duration',
    expired: 'expired',
    lga: 'lga',
    live: 'live',
    locationsSelected: 'locationsSelected',
    name: 'name',
    pending: 'pending',
    price: 'price',
    state: 'state',
    title: 'title',
    trafficRate: 'trafficRate',
    validity: 'validity',
};
