module.exports.input = {
    address: 'address',
    amount: 'amount',
    commercialId: 'commercialId',
    country: 'country',
    duration: 'duration',
    lga: 'lga',
    locationsSelected: 'locationsSelected',
    name: 'name',
    price: 'price',
    state: 'state',
    status: 'status',
    title: 'title',
    trafficRate: 'trafficRate',
    validity: 'validity',
};
