module.exports.input = {
    address: 'address',
    adminImage: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    amount: 'amount',
    approved: 'approved',
    author: 'Neonatar Admin',
    category: 'category',
    commercialId: 'commercialId',
    content1: 'Welcome to NeoNatar, please tell us about your issue. We will get back to you as',
    content2: 'soon as possible',
    country: 'country',
    duration: 'duration',
    expired: 'expired',
    lga: 'lga',
    live: 'live',
    locationsSelected: 'locationsSelected',
    name: 'name',
    pending: 'pending',
    price: 'price',
    state: 'state',
    title: 'title',
    trafficRate: 'trafficRate',
    validity: 'validity',
};
